# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "YOUR_CLIENT_ID"
name = "shop-chat-agent"
handle = "shop-chat-agent"
application_url = "https://shop-chat-agent.com"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_customers,customer_read_orders,customer_read_store_credit_account_transactions,customer_read_store_credit_accounts,unauthenticated_read_product_listings"

[auth]
redirect_urls = [ "https://shop-chat-agent.com/api/auth" ]

[pos]
embedded = false

[mcp.customer_authentication]
redirect_uris = [
  "https://shop-chat-agent.com/callback"
]

[app_proxy]
url = "https://shop-chat-agent.com"
subpath = "apps/mattressai"
prefix = "apps"

[webhooks]
api_version = "2025-04"
[[webhooks.subscriptions]]
uri = "/webhooks/customers/data_request"
topic = "customers/data_request"
[[webhooks.subscriptions]]
uri = "/webhooks/customers/redact"
topic = "customers/redact"
[[webhooks.subscriptions]]
uri = "/webhooks/shop/redact"
topic = "shop/redact"

[[extensions]]
name = "mattressai-widget"
type = "theme"
[[extensions.target]]
type = "theme_app_extension"
name = "MattressAI App Embed"
