# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6b1ed5786311fcaad075b3a7cc5f348e"
name = "MattressAI"
application_url = "https://maishopdash.web.app/"
embedded = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [
  "products/update",
  "shop/update",
  "orders/create",
  "inventory_levels/update",
  "customers/delete",
  "orders/updated",
  "app/uninstalled",
  "app_subscriptions/update",
  "orders/paid",
  "products/create",
  "orders/cancelled",
  "customers/create",
  "customers/update",
  "orders/fulfilled",
  "products/delete"
]
  uri = "https://us-central1-mattressai2.cloudfunctions.net/api"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_orders,read_products"

[auth]
redirect_urls = [
  "https://us-central1-mattressai2.cloudfunctions.net/api",
  "http://localhost:5174/auth/callback"
]

[app_proxy]
url = "https://maishopdash.web.app/api"
subpath = "proxy"
prefix = "apps"
