# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6b1ed5786311fcaad075b3a7cc5f348e"
name = "MattressAI"
application_url = "https://mattressaishopify.vercel.app/"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [
  "app/uninstalled",
  "orders/fulfilled",
  "products/delete",
  "products/create",
  "orders/updated",
  "products/update",
  "inventory_levels/update",
  "app_subscriptions/update",
  "orders/paid",
  "shop/update",
  "orders/create",
  "orders/cancelled",
  "customers/create",
  "customers/update",
  "customers/delete"
]
  uri = "/api/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_orders,read_products"

[auth]
redirect_urls = [
  "https://mattressaishopify.vercel.app/auth/callback",
  "http://localhost:5174/auth/callback"
]

[app_proxy]
url = "https://mattressaishopify.vercel.app/apps/mattressai"
subpath = "mattressai"
prefix = "apps"
