/**
 * Port interface for embedding operations
 * Allows swapping between different embedding providers (OpenAI, Cohere, etc.)
 */
export interface EmbeddingPort {
  /**
   * Generate embeddings for text content
   * @param texts Array of text strings to embed
   * @param options Configuration options for embedding generation
   * @returns Array of embedding vectors
   */
  generateEmbeddings(texts: string[], options?: EmbeddingOptions): Promise<number[][]>;

  /**
   * Get the dimensionality of embeddings generated by this provider
   */
  getEmbeddingDimensions(): number;

  /**
   * Health check for the embedding service
   */
  isHealthy(): Promise<boolean>;
}

export interface EmbeddingOptions {
  model?: string;
  encodingFormat?: 'float' | 'base64';
  dimensions?: number; // For models that support dimensionality reduction
  user?: string; // For usage tracking
}


